//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5_CSRF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusUpdate
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
        public System.DateTime StatusDate { get; set; }
    }
}
