//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_CryptoStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordMD5 { get; set; }
    }
}
